# Generated by Django 3.2.5 on 2021-11-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
