# Generated by Django 3.2.5 on 2021-11-29 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_user_profile_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=200)),
                ('registration', models.CharField(max_length=5)),
                ('is_Booked', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SeftyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=200)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
        migrations.RenameModel(
            old_name='User_profile',
            new_name='UserProfile',
        ),
        migrations.DeleteModel(
            name='Car_profile',
        ),
    ]
