# Generated by Django 3.2.5 on 2021-11-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20211129_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_Booked',
            field=models.BooleanField(default=False),
        ),
    ]
